// 北京地铁基础数据
// 北京地铁截至2025年1月29条线路522座车站最新数据
// istransfer属性：1表示换乘站（线路数>1），0表示非换乘站

const metroData = {
    stations: [
        { name: "环球度假区", lines:[1, 7], cardmode: 1, istransfer: 1},
        { name: "花庄", lines: [1, 7], cardmode: 1, istransfer: 1},
        { name: "土桥", lines: [1], cardmode: 0, istransfer: 0},
        { name: "临河里", lines: [1], cardmode: 0, istransfer: 0},
        { name: "梨园", lines: [1], cardmode: 0, istransfer: 0},
        { name: "九棵树", lines: [1], cardmode: 0, istransfer: 0},
        { name: "果园", lines: [1], cardmode: 0, istransfer: 0},
        { name: "通州北苑", lines: [1], cardmode: 0, istransfer: 0},
        { name: "八里桥", lines: [1], cardmode: 0, istransfer: 0},
        { name: "管庄", lines: [1], cardmode: 0, istransfer: 0},
        { name: "双桥", lines: [1], cardmode: 0, istransfer: 0},
        { name: "传媒大学", lines: [1], cardmode: 0, istransfer: 0},
        { name: "高碑店", lines: [1], cardmode: 0, istransfer: 0},
        { name: "四惠东", lines: [1], cardmode: 0, istransfer: 0},
        { name: "四惠", lines: [1], cardmode: 0, istransfer: 0},
        { name: "大望路", lines: [1, 14], cardmode: 1, istransfer: 1},
        { name: "国贸", lines: [1, 10], cardmode: 1, istransfer: 1},
        { name: "永安里", lines: [1], cardmode: 0, istransfer: 0},
        { name: "建国门", lines: [1, 2], cardmode: 1, istransfer: 1},
        { name: "东单", lines: [1, 5], cardmode: 1, istransfer: 1},
        { name: "王府井", lines: [1, 8], cardmode: 1, istransfer: 1},
        { name: "天安门东", lines: [1], cardmode: 1, istransfer: 0},
        { name: "天安门西", lines: [1], cardmode: 1, istransfer: 0},
        { name: "西单", lines: [1, 4], cardmode: 1, istransfer: 1},
        { name: "复兴门", lines: [1, 2], cardmode: 1, istransfer: 1},
        { name: "南礼士路", lines: [1], cardmode: 0, istransfer: 0},
        { name: "木樨地", lines: [1, 16], cardmode: 0, istransfer: 1},
        { name: "军事博物馆", lines: [1, 9], cardmode: 1, istransfer: 1},
        { name: "公主坟", lines: [1, 10], cardmode: 1, istransfer: 1},
        { name: "万寿路", lines: [1], cardmode: 0, istransfer: 0},
        { name: "五棵松", lines: [1], cardmode: 0, istransfer: 0},
        { name: "玉泉路", lines: [1], cardmode: 0, istransfer: 0},
        { name: "八宝山", lines: [1], cardmode: 0, istransfer: 0},
        { name: "八角游乐园", lines: [1], cardmode: 0, istransfer: 0},
        { name: "古城", lines: [1], cardmode: 0, istransfer: 0},
        { name: "苹果园", lines: [1, "S1"], cardmode: 1, istransfer: 1},
        { name: "东直门", lines: [2, 13, "sdjc"], cardmode: 1, istransfer: 1},
        { name: "雍和宫", lines: [2, 5], cardmode: 1, istransfer: 1},
        { name: "安定门", lines: [2], cardmode: 0, istransfer: 0},
        { name: "鼓楼大街", lines: [2, 8], cardmode: 1, istransfer: 1},
        { name: "积水潭", lines: [2, 19], cardmode: 1, istransfer: 1},
        { name: "西直门", lines: [2, 4, 13], cardmode: 1, istransfer: 1},
        { name: "车公庄", lines: [2, 6], cardmode: 1, istransfer: 1},
        { name: "阜成门", lines: [2], cardmode: 0, istransfer: 0},
        { name: "长椿街", lines: [2], cardmode: 0, istransfer: 0},
        { name: "宣武门", lines: [2, 4], cardmode: 1, istransfer: 1},
        { name: "和平门", lines: [2], cardmode: 0, istransfer: 0},
        { name: "前门", lines: [2, 8], cardmode: 1, istransfer: 1},
        { name: "崇文门", lines: [2, 5], cardmode: 1, istransfer: 1},
        { name: "北京站", lines: [2], cardmode: 1, istransfer: 0},
        { name: "朝阳门", lines: [2, 6], cardmode: 1, istransfer: 1},
        { name: "东四十条", lines: [2, 3], cardmode: 0, istransfer: 1},
        { name: "东坝北", lines: [3, 12], cardmode: 0, istransfer: 1},
        { name: "东坝", lines: [3], cardmode: 0, istransfer: 0},
        { name: "东坝南", lines: [3], cardmode: 0, istransfer: 0},
        { name: "姚家园", lines: [3], cardmode: 0, istransfer: 0},
        { name: "朝阳站", lines: [3], cardmode: 0, istransfer: 0},
        { name: "石佛营", lines: [3], cardmode: 0, istransfer: 0},
        { name: "朝阳公园", lines: [3, 14], cardmode: 1, istransfer: 1},
        { name: "团结湖", lines: [3, 10], cardmode: 0, istransfer: 1},
        { name: "工人体育场", lines: [3, 17], cardmode: 0, istransfer: 1},
        { name: "安河桥北", lines: [4], cardmode: 0, istransfer: 0},
        { name: "北宫门", lines: [4], cardmode: 1, istransfer: 0},
        { name: "西苑", lines: [4, 16], cardmode: 1, istransfer: 1},
        { name: "圆明园", lines: [4], cardmode: 1, istransfer: 0},
        { name: "北京大学东门", lines: [4], cardmode: 1, istransfer: 0},
        { name: "中关村", lines: [4], cardmode: 0, istransfer: 0},
        { name: "海淀黄庄", lines: [4, 10], cardmode: 1, istransfer: 1},
        { name: "人民大学", lines: [4, 12], cardmode: 0, istransfer: 1},
        { name: "魏公村", lines: [4], cardmode: 0, istransfer: 0},
        { name: "国家图书馆", lines: [4, 9, 16], cardmode: 1, istransfer: 1},
        { name: "动物园", lines: [4], cardmode: 1, istransfer: 0},
        { name: "新街口", lines: [4], cardmode: 0, istransfer: 0},
        { name: "平安里", lines: [4, 6, 19], cardmode: 1, istransfer: 1},
        { name: "西四", lines: [4], cardmode: 0, istransfer: 0},
        { name: "灵境胡同", lines: [4], cardmode: 0, istransfer: 0},
        { name: "菜市口", lines: [4, 7], cardmode: 1, istransfer: 1},
        { name: "陶然亭", lines: [4], cardmode: 0, istransfer: 0},
        { name: "北京南站", lines: [4, 14], cardmode: 1, istransfer: 1},
        { name: "马家堡", lines: [4], cardmode: 0, istransfer: 0},
        { name: "角门西", lines: [4, 10], cardmode: 1, istransfer: 1},
        { name: "公益西桥", lines: [4], cardmode: 0, istransfer: 0},
        { name: "新宫", lines: [4], cardmode: 1, istransfer: 0},
        { name: "西红门", lines: [4], cardmode: 0, istransfer: 0},
        { name: "高米店北", lines: [4], cardmode: 0, istransfer: 0},
        { name: "高米店", lines: [4], cardmode: 0, istransfer: 0},
        { name: "高米店南", lines: [4], cardmode: 0, istransfer: 0},
        { name: "枣园", lines: [4], cardmode: 0, istransfer: 0},
        { name: "清源路", lines: [4], cardmode: 0, istransfer: 0},
        { name: "黄村西大街", lines: [4], cardmode: 0, istransfer: 0},
        { name: "黄村火车站", lines: [4], cardmode: 0, istransfer: 0},
        { name: "义和庄", lines: [4], cardmode: 0, istransfer: 0},
        { name: "生物医药基地", lines: [4], cardmode: 0, istransfer: 0},
        { name: "天宫院", lines: [4], cardmode: 0, istransfer: 0},
        { name: "天通苑北", lines: [5], cardmode: 0, istransfer: 0},
        { name: "天通苑", lines: [5], cardmode: 0, istransfer: 0},
        { name: "天通苑南", lines: [5], cardmode: 0, istransfer: 0},
        { name: "立水桥", lines: [5, 13], cardmode: 1, istransfer: 1},
        { name: "立水桥南", lines: [5], cardmode: 0, istransfer: 0},
        { name: "北苑路北", lines: [5], cardmode: 0, istransfer: 0},
        { name: "大屯路东", lines: [5, 15], cardmode: 1, istransfer: 1},
        { name: "惠新西街北口", lines: [5], cardmode: 0, istransfer: 0},
        { name: "惠新西街南口", lines: [5, 10], cardmode: 1, istransfer: 1},
        { name: "和平西桥", lines: [5, 12], cardmode: 0, istransfer: 1},
        { name: "和平里北街", lines: [5], cardmode: 0, istransfer: 0},
        { name: "北新桥", lines: [5, "sdjc"], cardmode: 1, istransfer: 1},
        { name: "张自忠路", lines: [5], cardmode: 0, istransfer: 0},
        { name: "东四", lines: [5, 6], cardmode: 1, istransfer: 1},
        { name: "灯市口", lines: [5], cardmode: 0, istransfer: 0},
        { name: "磁器口", lines: [5, 7], cardmode: 1, istransfer: 1},
        { name: "天坛东门", lines: [5], cardmode: 1, istransfer: 0},
        { name: "蒲黄榆", lines: [5, 14], cardmode: 1, istransfer: 1},
        { name: "刘家窑", lines: [5], cardmode: 0, istransfer: 0},
        { name: "宋家庄", lines: [5, 10, "yz"], cardmode: 1, istransfer: 1},
        { name: "潞城", lines: [6], cardmode: 0, istransfer: 0},
        { name: "东夏园", lines: [6], cardmode: 0, istransfer: 0},
        { name: "郝家府", lines: [6], cardmode: 0, istransfer: 0},
        { name: "北运河东", lines: [6], cardmode: 0, istransfer: 0},
        { name: "北运河西", lines: [6], cardmode: 0, istransfer: 0},
        { name: "通运门", lines: [6], cardmode: 0, istransfer: 0},
        { name: "通州北关", lines: [6], cardmode: 0, istransfer: 0},
        { name: "物资学院路", lines: [6], cardmode: 0, istransfer: 0},
        { name: "草房", lines: [6], cardmode: 0, istransfer: 0},
        { name: "常营", lines: [6], cardmode: 0, istransfer: 0},
        { name: "黄渠", lines: [6], cardmode: 0, istransfer: 0},
        { name: "褡裢坡", lines: [6], cardmode: 0, istransfer: 0},
        { name: "青年路", lines: [6], cardmode: 0, istransfer: 0},
        { name: "十里堡", lines: [6], cardmode: 0, istransfer: 0},
        { name: "金台路", lines: [6, 14], cardmode: 1, istransfer: 1},
        { name: "呼家楼", lines: [6, 10], cardmode: 1, istransfer: 1},
        { name: "东大桥", lines: [6], cardmode: 1, istransfer: 0},
        { name: "南锣鼓巷", lines: [6, 8], cardmode:1, istransfer: 1},
        { name: "北海北", lines: [6], cardmode: 1, istransfer: 0},
        { name: "车公庄西", lines: [6], cardmode: 0, istransfer: 0},
        { name: "二里沟", lines: [6, 16], cardmode: 0, istransfer: 1},
        { name: "白石桥南", lines: [6, 9], cardmode: 1, istransfer: 1},
        { name: "花园桥", lines: [6], cardmode: 0, istransfer: 0},
        { name: "慈寿寺", lines: [6, 10], cardmode: 1, istransfer: 1},
        { name: "海淀五路居", lines: [6], cardmode: 0, istransfer: 0},
        { name: "田村", lines: [6], cardmode: 0, istransfer: 0},
        { name: "廖公庄", lines: [6], cardmode: 0, istransfer: 0},
        { name: "西黄村", lines: [6], cardmode: 0, istransfer: 0},
        { name: "杨庄", lines: [6], cardmode: 0, istransfer: 0},
        { name: "金安桥", lines: [6, 11, "S1"], cardmode: 0, istransfer: 1},
        { name: "高楼金", lines: [7], cardmode: 0, istransfer: 0},
        { name: "群芳", lines: [7], cardmode: 0, istransfer: 0},
        { name: "万盛东", lines: [7], cardmode: 0, istransfer: 0},
        { name: "万盛西", lines: [7], cardmode: 0, istransfer: 0},
        { name: "黑庄户", lines: [7], cardmode: 0, istransfer: 0},
        { name: "郎辛庄", lines: [7], cardmode: 0, istransfer: 0},
        { name: "黄厂", lines: [7], cardmode: 0, istransfer: 0},
        { name: "焦化厂", lines: [7], cardmode: 0, istransfer: 0},
        { name: "双合", lines: [7], cardmode: 0, istransfer: 0},
        { name: "垡头", lines: [7], cardmode: 0, istransfer: 0},
        { name: "欢乐谷景区", lines: [7], cardmode: 0, istransfer: 0},
        { name: "南楼梓庄", lines: [7], cardmode: 0, istransfer: 0},
        { name: "化工", lines: [7], cardmode: 0, istransfer: 0},
        { name: "百子湾", lines: [7], cardmode: 0, istransfer: 0},
        { name: "大郊亭", lines: [7], cardmode: 0, istransfer: 0},
        { name: "九龙山", lines: [7, 14], cardmode: 1, istransfer: 1},
        { name: "双井", lines: [7, 10], cardmode: 1, istransfer: 1},
        { name: "广渠门外", lines: [7], cardmode: 0, istransfer: 0},
        { name: "广渠门内", lines: [7], cardmode: 0, istransfer: 0},
        { name: "桥湾", lines: [7], cardmode: 0, istransfer: 0},
        { name: "珠市口", lines: [7, 8], cardmode: 1, istransfer: 1},
        { name: "虎坊桥", lines: [7], cardmode: 0, istransfer: 0},
        { name: "广安门内", lines: [7], cardmode: 0, istransfer: 0},
        { name: "达官营", lines: [7, 16], cardmode: 0, istransfer: 1},
        { name: "湾子", lines: [7], cardmode: 0, istransfer: 0},
        { name: "北京西站", lines: [7, 9], cardmode: 1, istransfer: 1},
        { name: "朱辛庄", lines: [8, "cp"], cardmode: 1, istransfer: 1},
        { name: "育知路", lines: [8], cardmode: 0, istransfer: 0},
        { name: "平西府", lines: [8], cardmode: 0, istransfer: 0},
        { name: "回龙观东大街", lines: [8], cardmode: 0, istransfer: 0},
        { name: "霍营", lines: [8, 13], cardmode: 1, istransfer: 1},
        { name: "育新", lines: [8], cardmode: 0, istransfer: 0},
        { name: "西小口", lines: [8], cardmode: 0, istransfer: 0},
        { name: "永泰庄", lines: [8], cardmode: 0, istransfer: 0},
        { name: "林萃桥", lines: [8], cardmode: 0, istransfer: 0},
        { name: "森林公园南门", lines: [8], cardmode: 0, istransfer: 0},
        { name: "奥林匹克公园", lines: [8, 15], cardmode:1, istransfer: 1},
        { name: "奥体中心", lines: [8], cardmode: 0, istransfer: 0},
        { name: "北土城", lines: [8, 10], cardmode: 1, istransfer: 1},
        { name: "安华桥", lines: [8, 12], cardmode: 0, istransfer: 1},
        { name: "安德里北街", lines: [8], cardmode: 0, istransfer: 0},
        { name: "什刹海", lines: [8], cardmode: 1, istransfer: 0},
        { name: "中国美术馆", lines: [8], cardmode: 1, istransfer: 0},
        { name: "金鱼胡同", lines: [8], cardmode: 0, istransfer: 0},
        { name: "天桥", lines: [8], cardmode: 0, istransfer: 0},
        { name: "永定门外", lines: [8, 14], cardmode: 1, istransfer: 1},
        { name: "木樨园", lines: [8], cardmode: 0, istransfer: 0},
        { name: "海户屯", lines: [8], cardmode: 0, istransfer: 0},
        { name: "大红门南", lines: [8], cardmode: 0, istransfer: 0},
        { name: "和义", lines: [8], cardmode: 0, istransfer: 0},
        { name: "东高地", lines: [8], cardmode: 0, istransfer: 0},
        { name: "火箭万源", lines: [8], cardmode: 0, istransfer: 0},
        { name: "五福堂", lines: [8], cardmode: 0, istransfer: 0},
        { name: "德茂", lines: [8], cardmode: 0, istransfer: 0},
        { name: "瀛海", lines: [8], cardmode: 0, istransfer: 0},
        { name: "白锥子", lines: [9], cardmode: 0, istransfer: 0},
        { name: "六里桥东", lines: [9], cardmode: 0, istransfer: 0},
        { name: "六里桥", lines: [9, 10], cardmode: 1, istransfer: 1},
        { name: "七里庄", lines: [9, 14], cardmode: 1, istransfer: 1},
        { name: "丰台东大街", lines: [9], cardmode: 0, istransfer: 0},
        { name: "丰台南路", lines: [9, 16], cardmode: 0, istransfer: 1},
        { name: "科怡路", lines: [9], cardmode: 0, istransfer: 0},
        { name: "丰台科技园", lines: [9], cardmode: 0, istransfer: 0},
        { name: "郭公庄", lines: [9, "fs"], cardmode: 0, istransfer: 1},
        { name: "苏州街", lines: [10, 16], cardmode: 0, istransfer: 1},
        { name: "巴沟", lines: [10, "xj"], cardmode: 0, istransfer: 1},
        { name: "火器营", lines: [10], cardmode: 0, istransfer: 0},
        { name: "长春桥", lines: [10, 12], cardmode: 0, istransfer: 1},
        { name: "车道沟", lines: [10], cardmode: 0, istransfer: 0},
        { name: "西钓鱼台", lines: [10], cardmode: 0, istransfer: 0},
        { name: "莲花桥", lines: [10], cardmode: 0, istransfer: 0},
        { name: "西局", lines: [10, 14], cardmode: 1, istransfer: 1},
        { name: "泥洼", lines: [10], cardmode: 0, istransfer: 0},
        { name: "丰台站", lines: [10, 16], cardmode: 0, istransfer: 1},
        { name: "首经贸", lines: [10, "fs"], cardmode: 0, istransfer: 1},
        { name: "纪家庙", lines: [10], cardmode: 0, istransfer: 0},
        { name: "草桥", lines: [10, 19, "dxjc"], cardmode: 1, istransfer: 1},
        { name: "角门东", lines: [10], cardmode: 0, istransfer: 0},
        { name: "大红门", lines: [10], cardmode: 0, istransfer: 0},
        { name: "石榴庄", lines: [10], cardmode: 0, istransfer: 0},
        { name: "成寿寺", lines: [10], cardmode: 0, istransfer: 0},
        { name: "分钟寺", lines: [10], cardmode: 0, istransfer: 0},
        { name: "十里河", lines: [10, 14, 17], cardmode: 1, istransfer: 1},
        { name: "潘家园", lines: [10], cardmode: 0, istransfer: 0},
        { name: "劲松", lines: [10], cardmode: 0, istransfer: 0},
        { name: "金台夕照", lines: [10], cardmode: 1, istransfer: 0},
        { name: "农业展览馆", lines: [10], cardmode: 0, istransfer: 0},
        { name: "亮马桥", lines: [10], cardmode: 0, istransfer: 0},
        { name: "三元桥", lines: [10, 12, "sdjc"], cardmode: 1, istransfer: 1},
        { name: "太阳宫", lines: [10, 17], cardmode: 0, istransfer: 1},
        { name: "芍药居", lines: [10, 13], cardmode: 1, istransfer: 1},
        { name: "安贞门", lines: [10], cardmode: 0, istransfer: 0},
        { name: "健德门", lines: [10], cardmode: 0, istransfer: 0},
        { name: "牡丹园", lines: [10, 19], cardmode: 1, istransfer: 1},
        { name: "西土城", lines: [10, "cp"], cardmode: 0, istransfer: 1},
        { name: "知春路", lines: [10, 13], cardmode: 1, istransfer: 1},
        { name: "知春里", lines: [10], cardmode: 0, istransfer: 0},
        { name: "新首钢", lines: [11], cardmode: 0, istransfer: 0},
        { name: "北辛安", lines: [11], cardmode: 0, istransfer: 0},
        { name: "模式口", lines: [11], cardmode: 0, istransfer: 0},
        { name: "四季青桥", lines: [12], cardmode: 0, istransfer: 0},
        { name: "蓝靛厂", lines: [12], cardmode: 0, istransfer: 0},
        { name: "苏州桥", lines: [12], cardmode: 0, istransfer: 0},
        { name: "大钟寺", lines: [12, 13], cardmode: 0, istransfer: 1},
        { name: "蓟门桥", lines: [12, "cp"], cardmode: 0, istransfer: 1},
        { name: "北太平庄", lines: [12, 19], cardmode: 0, istransfer: 1},
        { name: "马甸桥", lines: [12], cardmode: 0, istransfer: 0},
        { name: "安贞桥", lines: [12], cardmode: 0, istransfer: 0},
        { name: "光熙门", lines: [12, 13], cardmode: 0, istransfer: 1},
        { name: "西坝河", lines: [12, 17], cardmode: 0, istransfer: 1},
        { name: "将台西", lines: [12], cardmode: 0, istransfer: 0},
        { name: "高家园", lines: [12], cardmode: 0, istransfer: 0},
        { name: "驼房营", lines: [12], cardmode: 0, istransfer: 0},
        { name: "东坝西", lines: [12], cardmode: 0, istransfer: 0},
        { name: "五道口", lines: [13], cardmode: 0, istransfer: 0},
        { name: "上地", lines: [13], cardmode: 0, istransfer: 0},
        { name: "清河站", lines: [13, "cp"], cardmode: 1, istransfer: 1},
        { name: "西二旗", lines: [13, "cp"], cardmode: 1, istransfer: 1},
        { name: "龙泽", lines: [13], cardmode: 0, istransfer: 0},
        { name: "回龙观", lines: [13], cardmode: 0, istransfer: 0},
        { name: "北苑", lines: [13], cardmode: 0, istransfer: 0},
        { name: "望京西", lines: [13, 15], cardmode: 1, istransfer: 1},
        { name: "柳芳", lines: [13], cardmode: 0, istransfer: 0},
        { name: "善各庄", lines: [14], cardmode: 0, istransfer: 0},
        { name: "来广营", lines: [14], cardmode: 0, istransfer: 0},
        { name: "东湖渠", lines: [14], cardmode: 0, istransfer: 0},
        { name: "望京", lines: [14, 15], cardmode: 1, istransfer: 1},
        { name: "阜通", lines: [14], cardmode: 0, istransfer: 0},
        { name: "望京南", lines: [14], cardmode: 0, istransfer: 0},
        { name: "将台", lines: [14], cardmode: 0, istransfer: 0},
        { name: "东风北桥", lines: [14], cardmode: 0, istransfer: 0},
        { name: "枣营", lines: [14], cardmode: 0, istransfer: 0},
        { name: "平乐园", lines: [14], cardmode: 0, istransfer: 0},
        { name: "北工大西门", lines: [14], cardmode: 0, istransfer: 0},
        { name: "方庄", lines: [14], cardmode: 0, istransfer: 0},
        { name: "景泰", lines: [14], cardmode: 0, istransfer: 0},
        { name: "陶然桥", lines: [14], cardmode: 0, istransfer: 0},
        { name: "景风门", lines: [14, 19], cardmode: 1, istransfer: 1},
        { name: "西铁营", lines: [14], cardmode: 0, istransfer: 0},
        { name: "菜户营", lines: [14], cardmode: 0, istransfer: 0},
        { name: "丽泽商务区", lines: [14], cardmode: 0, istransfer: 0},
        { name: "东管头", lines: [14], cardmode: 0, istransfer: 0},
        { name: "大井", lines: [14], cardmode: 0, istransfer: 0},
        { name: "郭庄子", lines: [14], cardmode: 0, istransfer: 0},
        { name: "大瓦窑", lines: [14], cardmode: 0, istransfer: 0},
        { name: "园博园", lines: [14], cardmode: 0, istransfer: 0},
        { name: "张郭庄", lines: [14], cardmode: 0, istransfer: 0},
        { name: "俸伯", lines: [15], cardmode: 0, istransfer: 0},
        { name: "顺义", lines: [15], cardmode: 0, istransfer: 0},
        { name: "石门", lines: [15], cardmode: 0, istransfer: 0},
        { name: "南法信", lines: [15], cardmode: 0, istransfer: 0},
        { name: "后沙峪", lines: [15], cardmode: 0, istransfer: 0},
        { name: "花梨坎", lines: [15], cardmode: 0, istransfer: 0},
        { name: "国展", lines: [15], cardmode: 0, istransfer: 0},
        { name: "孙河", lines: [15], cardmode: 0, istransfer: 0},
        { name: "马泉营", lines: [15], cardmode: 0, istransfer: 0},
        { name: "崔各庄", lines: [15], cardmode: 0, istransfer: 0},
        { name: "望京东", lines: [15], cardmode: 0, istransfer: 0},
        { name: "关庄", lines: [15], cardmode: 0, istransfer: 0},
        { name: "安立路", lines: [15], cardmode: 0, istransfer: 0},
        { name: "北沙滩", lines: [15], cardmode: 0, istransfer: 0},
        { name: "六道口", lines: [15, "cp"], cardmode: 0, istransfer: 1},
        { name: "清华东路西口", lines: [15], cardmode: 0, istransfer: 0},
        { name: "北安河", lines: [16], cardmode: 0, istransfer: 0},
        { name: "温阳路", lines: [16], cardmode: 0, istransfer: 0},
        { name: "稻香湖路", lines: [16], cardmode: 0, istransfer: 0},
        { name: "屯佃", lines: [16], cardmode: 0, istransfer: 0},
        { name: "永丰", lines: [16], cardmode: 0, istransfer: 0},
        { name: "永丰南", lines: [16], cardmode: 0, istransfer: 0},
        { name: "西北旺", lines: [16], cardmode: 0, istransfer: 0},
        { name: "马连洼", lines: [16], cardmode: 0, istransfer: 0},
        { name: "农大南路", lines: [16], cardmode: 0, istransfer: 0},
        { name: "万泉河桥", lines: [16], cardmode: 0, istransfer: 0},
        { name: "万寿寺", lines: [16], cardmode: 0, istransfer: 0},
        { name: "甘家口", lines: [16], cardmode: 0, istransfer: 0},
        { name: "玉渊潭东门", lines: [16], cardmode: 0, istransfer: 0},
        { name: "红莲南路", lines: [16], cardmode: 0, istransfer: 0},
        { name: "东管头南", lines: [16, "fs"], cardmode: 0, istransfer: 1},
        { name: "富丰桥", lines: [16], cardmode: 0, istransfer: 0},
        { name: "看丹", lines: [16], cardmode: 0, istransfer: 0},
        { name: "榆树庄", lines: [16], cardmode: 0, istransfer: 0},
        { name: "洪泰庄", lines: [16], cardmode: 0, istransfer: 0},
        { name: "宛平城", lines: [16], cardmode: 0, istransfer: 0},
        { name: "周家庄", lines: [17], cardmode: 0, istransfer: 0},
        { name: "十八里店", lines: [17], cardmode: 0, istransfer: 0},
        { name: "北神树", lines: [17], cardmode: 0, istransfer: 0},
        { name: "次渠北", lines: [17], cardmode: 0, istransfer: 0},
        { name: "次渠", lines: [17, "yz"], cardmode: 0, istransfer: 1},
        { name: "嘉会湖", lines: [17], cardmode: 0, istransfer: 0},
        { name: "新发地", lines: [19], cardmode: 0, istransfer: 0},
        { name: "牛街", lines: [19], cardmode: 0, istransfer: 0},
        { name: "太平桥", lines: [19], cardmode: 0, istransfer: 0},
        { name: "花乡东桥", lines: ["fs"], cardmode: 0, istransfer: 0},
        { name: "白盆窑", lines: ["fs"], cardmode: 0, istransfer: 0},
        { name: "大葆台", lines: ["fs"], cardmode: 0, istransfer: 0},
        { name: "稻田", lines: ["fs"], cardmode: 0, istransfer: 0},
        { name: "长阳", lines: ["fs"], cardmode: 0, istransfer: 0},
        { name: "篱笆房", lines: ["fs"], cardmode: 0, istransfer: 0},
        { name: "广阳城", lines: ["fs"], cardmode: 0, istransfer: 0},
        { name: "良乡大学城北", lines: ["fs"], cardmode: 0, istransfer: 0},
        { name: "良乡大学城", lines: ["fs"], cardmode: 0, istransfer: 0},
        { name: "良乡大学城西", lines: ["fs"], cardmode: 0, istransfer: 0},
        { name: "良乡南关", lines: ["fs"], cardmode: 0, istransfer: 0},
        { name: "苏庄", lines: ["fs"], cardmode: 0, istransfer: 0},
        { name: "阎村东", lines: ["fs", "yf"], cardmode: 0, istransfer: 1},
        { name: "昌平西山口", lines: ["fs", "yf"], cardmode: 0, istransfer: 1},
        { name: "十三陵景区", lines: ["cp"], cardmode: 0, istransfer: 0},
        { name: "昌平", lines: ["cp"], cardmode: 0, istransfer: 0},
        { name: "昌平东关", lines: ["cp"], cardmode: 0, istransfer: 0},
        { name: "北邵洼", lines: ["cp"], cardmode: 0, istransfer: 0},
        { name: "南邵", lines: ["cp"], cardmode: 0, istransfer: 0},
        { name: "沙河高教园", lines: ["cp"], cardmode: 0, istransfer: 0},
        { name: "沙河", lines: ["cp"], cardmode: 0, istransfer: 0},
        { name: "巩华城", lines: ["cp"], cardmode: 0, istransfer: 0},
        { name: "生命科学园", lines: ["cp"], cardmode: 0, istransfer: 0},
        { name: "朱房北", lines: ["cp"], cardmode: 0, istransfer: 0},
        { name: "清河小营桥", lines: ["cp"], cardmode: 0, istransfer: 0},
        { name: "学知园", lines: ["cp"], cardmode: 0, istransfer: 0},
        { name: "学院桥", lines: ["cp"], cardmode: 0, istransfer: 0},
        { name: "肖村", lines: ["yz"], cardmode: 0, istransfer: 0},
        { name: "小红门", lines: ["yz"], cardmode: 0, istransfer: 0},
        { name: "旧宫", lines: ["yz"], cardmode: 0, istransfer: 0},
        { name: "亦庄桥", lines: ["yz"], cardmode: 0, istransfer: 0},
        { name: "亦庄文化园", lines: ["yz"], cardmode: 0, istransfer: 0},
        { name: "万源街", lines: ["yz"], cardmode: 0, istransfer: 0},
        { name: "荣京东街", lines: ["yz"], cardmode: 0, istransfer: 0},
        { name: "荣昌东街", lines: ["yz", "yzt1"], cardmode: 0, istransfer: 1},
        { name: "同济南路", lines: ["yz"], cardmode: 0, istransfer: 0},
        { name: "经海路", lines: ["yz"], cardmode: 0, istransfer: 0},
        { name: "次渠南", lines: ["yz"], cardmode: 0, istransfer: 0},
        { name: "亦庄火车站", lines: ["yz"], cardmode: 0, istransfer: 0},
        { name: "紫草坞", lines: ["yf"], cardmode: 0, istransfer: 0},
        { name: "阎村", lines: ["yf"], cardmode: 0, istransfer: 0},
        { name: "星城", lines: ["yf"], cardmode: 0, istransfer: 0},
        { name: "大石河东", lines: ["yf"], cardmode: 0, istransfer: 0},
        { name: "马各庄", lines: ["yf"], cardmode: 0, istransfer: 0},
        { name: "饶乐府", lines: ["yf"], cardmode: 0, istransfer: 0},
        { name: "房山城关", lines: ["yf"], cardmode: 0, istransfer: 0},
        { name: "燕山", lines: ["yf"], cardmode: 0, istransfer: 0},
        { name: "四道桥", lines: ["S1"], cardmode: 0, istransfer: 0},
        { name: "桥户营", lines: ["S1"], cardmode: 0, istransfer: 0},
        { name: "上岸", lines: ["S1"], cardmode: 0, istransfer: 0},
        { name: "栗园庄", lines: ["S1"], cardmode: 0, istransfer: 0},
        { name: "小园", lines: ["S1"], cardmode: 0, istransfer: 0},
        { name: "石厂", lines: ["S1"], cardmode: 0, istransfer: 0},
        { name: "颐和园西门", lines: ["xj"], cardmode: 0, istransfer: 0},
        { name: "茶棚", lines: ["xj"], cardmode: 0, istransfer: 0},
        { name: "万安", lines: ["xj"], cardmode: 0, istransfer: 0},
        { name: "国家植物园", lines: ["xj"], cardmode: 0, istransfer: 0},
        { name: "香山", lines: ["xj"], cardmode: 0, istransfer: 0},
        { name: "定海园", lines: ["yzt1"], cardmode: 0, istransfer: 0},
        { name: "定海园西", lines: ["yzt1"], cardmode: 0, istransfer: 0},
        { name: "经海一路", lines: ["yzt1"], cardmode: 0, istransfer: 0},
        { name: "亦创会展中心", lines: ["yzt1"], cardmode: 0, istransfer: 0},
        { name: "亦庄同仁", lines: ["yzt1"], cardmode: 0, istransfer: 0},
        { name: "鹿圈东", lines: ["yzt1"], cardmode: 0, istransfer: 0},
        { name: "泰河路", lines: ["yzt1"], cardmode: 0, istransfer: 0},
        { name: "九号村", lines: ["yzt1"], cardmode: 0, istransfer: 0},
        { name: "四海庄", lines: ["yzt1"], cardmode: 0, istransfer: 0},
        { name: "太和桥北", lines: ["yzt1"], cardmode: 0, istransfer: 0},
        { name: "瑞合庄", lines: ["yzt1"], cardmode: 0, istransfer: 0},
        { name: "融兴街", lines: ["yzt1"], cardmode: 0, istransfer: 0},
        { name: "屈庄", lines: ["yzt1"], cardmode: 0, istransfer: 0},
        { name: "老观里", lines: ["yzt1"], cardmode: 0, istransfer: 0},
        { name: "2号航站楼", lines: ["sdjc"], cardmode: 0, istransfer: 0},
        { name: "3号航站楼", lines: ["sdjc"], cardmode: 0, istransfer: 0},
        { name: "大兴新城", lines: ["dxjc"], cardmode: 0, istransfer: 0},
        { name: "大兴机场", lines: ["dxjc"], cardmode: 0, istransfer: 0},
      ],
      lines: [
        { id: 1, name: "1号线" },
        { id: 2, name: "2号线" },
        { id: 3, name: "3号线" },
        { id: 4, name: "4号线" },
        { id: 5, name: "5号线" },
        { id: 6, name: "6号线" },
        { id: 7, name: "7号线" },
        { id: 8, name: "8号线" },
        { id: 9, name: "9号线" },
        { id: 10, name: "10号线" },
        { id: 11, name: "11号线" },
        { id: 12, name: "12号线" },
        { id: 13, name: "13号线" },
        { id: 14, name: "14号线" },
        { id: 15, name: "15号线" },
        { id: 16, name: "16号线" },
        { id: 17, name: "17号线" },
        { id: 19, name: "19号线" },
        { id: "fs", name: "房山线" },
        { id: "cp", name: "昌平线" },
        { id: "yz", name: "亦庄线" },
        { id: "yf", name: "燕房线" },
        { id: "S1", name: "S1线" },
        { id: "xj", name: "西郊线" },
        { id: "yzt1", name: "亦庄T1线" },
        { id: "sdjc", name: "首都机场线" },
        { id: "dxjc", name: "大兴机场线" }
      ]
};

// 获取两个站点之间是否直接相连
function areStationsConnected(station1, station2) {
  // 获取站点对象
  const station1Obj = metroData.stations.find(s => s.name === station1);
  const station2Obj = metroData.stations.find(s => s.name === station2);
  
  if (!station1Obj || !station2Obj) return false;
  
  // 检查两站是否有共同线路
  for (const line1 of station1Obj.lines) {
    if (station2Obj.lines.includes(line1)) {
      // 有共同线路，还需要检查是否相邻
      // 这里简化处理，假设有共同线路的站点可能相连
      // 实际应用中需要完整的线路站点顺序数据
      return true;
    }
  }
  
  return false;
}

// 获取与指定站点直接相连的所有站点
function getConnectedStations(stationName) {
  const station = metroData.stations.find(s => s.name === stationName);
  if (!station) return [];
  
  // 获取该站点所在的所有线路
  const stationLines = station.lines;
  
  // 查找同线路的相邻站点
  // 注意：这里是简化实现，实际应用中需要完整的线路站点顺序数据
  const connectedStations = [];
  
  metroData.stations.forEach(s => {
    if (s.name !== stationName) {
      // 检查是否有共同线路
      for (const line of stationLines) {
        if (s.lines.includes(line)) {
          // 有共同线路，假设可能相连
          // 实际应用中需要检查是否相邻
          connectedStations.push(s.name);
          break;
        }
      }
    }
  });
  
  return connectedStations;
}

// 导出模块
export { metroData, areStationsConnected, getConnectedStations };